### PR TITLE
fix download from new website design

### PR DESCRIPTION
**Pull request by Sawalhah**
after Coursehunters redesign the website #18 
the download shows error `TypeError: Cannot read property 'toString' of undefined`
now it works again

### CODE REVIEW

**Comment by msarsha** [comment]
Running it locally does not download for me:

for example:
`node index.js -u https://coursehunters.net/course/polnoe-vvedenie-v-react-v5-reshoot`

**Comment by Sawalhah** [comment]
You need login to download paid courses

**Comment by msarsha** [comment]
It's a free one.

**Comment by Sawalhah** [comment]
this course has an issue
can you play it online via coursehunters ?

**Comment by a-eid** [comment]
👍 working for me.

**Comment by sankalpgaikwad** [comment]
internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module 'C:\Users\Sankalp Gaikwad\Desktop\colt\coureshunters'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:527:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by sankalpgaikwad** [comment]
Its not working

**Comment by darkgen** [comment]
> You need login to download paid courses

how i can login, can you write example pls?

**Comment by a-eid** [comment]
@darkgen 

`npm install -g https://github.com/Sawalhah/ch-download`
`coursehunters -e 'email' -p 'password' -u 'course url'`

**Comment by rapincx** [comment]
> @darkgen
> 
> `npm install -g https://github.com/Sawalhah/ch-download`
> `coursehunters -e 'email' -p 'password' -u 'course url'`

Now this downloader doesn't work with auth
Can error when get accessToken

**Comment by Sawalhah** [comment]
@rapincx 
what is the error message ?

**Comment by jaeyholic** [comment]
> @rapincx
> what is the error message ?

No error message, it just stops. I have tried several times. I have entered my login details but still doesn't work

**Comment by a-eid** [comment]
sometimes it doesn't work.

Screen Shot 2019-06-13 at 11 23 15 PM

**Comment by rapincx** [comment]
> sometimes it doesn't work.
> 
> Screen Shot 2019-06-13 at 11 23 15 PM

Problem in creating accessToken, cookie data wrong for current revision site

**Comment by Sawalhah** [comment]
Have you purchased the course ?
If not it wouldn't downloading

**Comment by a-eid** [comment]
@Sawalhah yes, it's working just fine on the site, 
also this does not happen with all courses.

**Pull request merged**
